#!/usr/bin/env python
#-*- coding: utf-8 -*-

##################################################
# Twittext
# - Simple text-based Twitter client
# - Hirotaka Kawata <info@techno-st.net>
# - http://www.techno-st.net/wiki/Twittext
##################################################

import twoauth
import os
import locale
import ConfigParser
import signal

def quit_me(signum = None, frame = None):
    exit()

if __name__ == "__main__":
    config_default = {
        "ckey": '3vqTk4hvNAno7NGzgBpdg',
        "csecret": 'PaeZx823Laxz3L5OF1R32zk9klW92tVyqn5mXjAoIw',
        }
    
    conf_name = 'settings.conf'
    conf_path  = os.path.join(
        os.path.dirname(__file__), conf_name)
    conf = ConfigParser.SafeConfigParser(config_default)
    
    if not os.path.isfile(conf_path):
        from gettoken import *
        (atoken, asecret, screen_name) = token(
            config_default["ckey"], 
            config_default["csecret"])
        
        conf.set("DEFAULT", "default_user", screen_name)
        conf.set("DEFAULT", "autoreload", 60)

        conf.add_section(screen_name)
        conf.set(screen_name, "atoken", atoken)
        conf.set(screen_name, "asecret", asecret)
        conf.set(screen_name, "footer", "")
        
        fp = open(conf_path, "w")
        conf.write(fp)
        fp.close()
    
    from main import *
    
    conf.read(conf_path)
    settings = dict(conf.items("DEFAULT"))
    user = dict(conf.items(settings["default_user"]))
    
    signal.signal(signal.SIGINT, quit_me)

    # Start
    tw = twittext(settings["ckey"], settings["csecret"],
                  user["atoken"], user["asecret"])
    tw.statusfooter = user["footer"]
    tw.autoreload = int(settings["autoreload"]) * 1000
    tw.run()
