#!/usr/bin/env python
#-*- coding: utf-8 -*-

###########################################################################
# Twittext
# - Simple text-based Twitter client
# - Hirotaka Kawata <info@techno-st.net>
# - http://www.techno-st.net/wiki/Twittext
#
#    Copyright (C) 2009 Hirotaka Kawata <info@techno-st.net>
#
#    This file is part of "Twittext".
#
#    Twittext is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Twittext is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Twittext.  If not, see <http://www.gnu.org/licenses/>.
#
###########################################################################

import twoauth
import os
import locale
import ConfigParser
import signal

__version__ = 0.5

def quit_me(signum = None, frame = None):
    exit()

if __name__ == "__main__":
    config_default = {
        "ckey": '3vqTk4hvNAno7NGzgBpdg',
        "csecret": 'PaeZx823Laxz3L5OF1R32zk9klW92tVyqn5mXjAoIw',
        }
    
    conf_name = 'settings.conf'
    conf_path  = os.path.join(
        os.path.dirname(__file__), conf_name)
    conf = ConfigParser.SafeConfigParser(config_default)
    
    if not os.path.isfile(conf_path):
        from gettoken import *
        (atoken, asecret, screen_name) = token(
            config_default["ckey"], 
            config_default["csecret"])
        
        conf.set("DEFAULT", "default_user", screen_name)
        conf.set("DEFAULT", "autoreload", 60)

        conf.add_section(screen_name)
        conf.set(screen_name, "atoken", atoken)
        conf.set(screen_name, "asecret", asecret)
        conf.set(screen_name, "footer", "")
        
        fp = open(conf_path, "w")
        conf.write(fp)
        fp.close()
    
    from main import *
    
    conf.read(conf_path)
    settings = dict(conf.items("DEFAULT"))
    user = dict(conf.items(settings["default_user"]))
    
    signal.signal(signal.SIGINT, quit_me)

    # Start
    tw = twittext(settings["ckey"], settings["csecret"],
                  user["atoken"], user["asecret"])
    tw.statusfooter = user["footer"]
    tw.autoreload = int(settings["autoreload"]) * 1000
    tw.run()
